name: "HA Gammu SMS"
version: "1.0.0"
slug: "ha_gammu"
description: "Gammu SMS fixed ID modem"
url: "https://github.com/yamestest/ha_gammu"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: services
boot: auto
init: false
options:
  device: /dev/serial/by-id/usb-HUAWEI_MOBILE_HUAWEI_MOBILE-if00-port0
schema:
  device: str
privileged:
  - SYS_RAWIO
devices:
  - /dev/serial/by-id/usb-HUAWEI_MOBILE_HUAWEI_MOBILE-if00-port0
